### ISSUE TITLE
The solution is not working in region eu-west-1

### ISSUE THREAD

**Issue by autonet-ai** [aws-samples/amazon-rekognition-custom-labels-feedback-solution#1]
The documentation says "Deploy CloudFormation stack in one of the AWS regions where you are using Amazon Rekognition Custom Labels." But the deployment fails if i change the region in the link to eu-west-1.

It fails on the step GTLabelVerificationPreLambda with error: Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: us-east-1. Please use this region to retry the request (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 2c779ae6-b8e2-4462-8721-a0bc13ee1e5a)

**Comment by darwaishx** [comment]
Added link to eu-west-1.
